apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qbx1iimff-go 
  janus-idp.io/tekton: qbx1iimff-go
  backstage.io/kubernetes-id: qbx1iimff-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qbx1iimff-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  