apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qbx1iimff-go-gitops
  description: This is GitOps manifest for qbx1iimff-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=qbx1iimff-go
    backstage.io/kubernetes-id: qbx1iimff-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qbx1iimff-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qbx1iimff-go
