apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qbx1iimff-go
  janus-idp.io/tekton: qbx1iimff-go
  backstage.io/kubernetes-id: qbx1iimff-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qbx1iimff-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
