apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qbx1iimff-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qbx1iimff-go 
  name: qbx1iimff-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qbx1iimff-go 
